### ISSUE TITLE
com.intellij.openapi.editor.ex.util.LexerEditorHighlighter(org.nixos.idea.lang.NixLexerAdapter): Error updating  after DocumentEventImpl

### ISSUE THREAD

**Issue by artspb** [NixOS/nix-idea#9]
Gogland 171.4694

<< com.intellij.openapi.editor.ex.util.LexerEditorHighlighter(org.nixos.idea.lang.NixLexerAdapter): Error updating  after DocumentEventImpl[myOffset=112, myOldLength=0, myNewLength=14, myOldString='', myNewString='"haproxy.conf"'].

com.intellij.openapi.editor.ex.util.LexerEditorHighlighter$InvalidStateException: com.intellij.openapi.editor.ex.util.LexerEditorHighlighter(org.nixos.idea.lang.NixLexerAdapter): Error updating  after DocumentEventImpl[myOffset=112, myOldLength=0, myNewLength=14, myOldString='', myNewString='"haproxy.conf"'].
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.documentChanged(LexerEditorHighlighter.java:327)
	at com.intellij.openapi.editor.impl.DocumentImpl.changedUpdate(DocumentImpl.java:789)
	at com.intellij.openapi.editor.impl.DocumentImpl.updateText(DocumentImpl.java:722)
	at com.intellij.openapi.editor.impl.DocumentImpl.insertString(DocumentImpl.java:480)
	at com.intellij.openapi.editor.EditorModificationUtil.insertStringAtCaretNoScrolling(EditorModificationUtil.java:130)
	at com.intellij.openapi.editor.EditorModificationUtil.insertStringAtCaret(EditorModificationUtil.java:95)
	at com.intellij.openapi.editor.EditorModificationUtil.insertStringAtCaret(EditorModificationUtil.java:87)
	at com.intellij.codeInsight.editorActions.PasteHandler.lambda$doPaste$0(PasteHandler.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1023)
	at com.intellij.codeInsight.editorActions.PasteHandler.doPaste(PasteHandler.java:194)
	at com.intellij.codeInsight.editorActions.PasteHandler.execute(PasteHandler.java:121)
	at com.intellij.codeInsight.editorActions.PasteHandler.doExecute(PasteHandler.java:74)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$4.perform(EditorActionHandler.java:217)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:214)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:98)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:107)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:86)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:215)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:232)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:570)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:619)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:618)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:633)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IndexOutOfBoundsException: Wrong offset: 112. Should be in range: [0, 101]
	at com.intellij.openapi.editor.ex.util.SegmentArray.offsetOutOfRange(SegmentArray.java:92)
	at com.intellij.openapi.editor.ex.util.SegmentArray.findSegmentIndex(SegmentArray.java:106)
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.documentChanged(LexerEditorHighlighter.java:173)
	... 35 more

**Comment by Mic92** [comment]
Hi, I am not maintaining this part in particular. But it would be probably more helpful for the developer, if you add a context to the problem like what have you done to get to this state (which file you edit) and what was the consequence.

**Comment by artspb** [comment]
I'm from JetBrains and currently processing exceptions reported by users. Unfortunately, there's no more information available about this particular exception.
